# Generated by Django 3.0.4 on 2020-04-20 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ciudad', '0001_initial'),
        ('PersonaNatural', '0001_initial'),
        ('Empresa', '0003_auto_20200419_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ano_creacion', models.DateField()),
                ('Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ciudad.Ciudad')),
                ('Empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Empresa.Empresa')),
                ('PersonaNatural', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonaNatural.PersonaNatural')),
            ],
        ),
    ]
