# Generated by Django 3.0.4 on 2020-04-21 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='PersonaNatural',
        ),
    ]
