# Generated by Django 3.0.4 on 2020-04-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arbitro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbitro',
            old_name='nombre',
            new_name='nombreA',
        ),
    ]
