# Generated by Django 3.0.4 on 2020-04-20 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alineacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripccion', models.CharField(max_length=200)),
                ('Alineacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alineacion.Alineacion')),
            ],
        ),
    ]
