# Generated by Django 3.0.4 on 2020-04-20 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alineacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_ingreso', models.CharField(max_length=200)),
                ('min_salida', models.CharField(max_length=200)),
                ('Equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipo.Equipo')),
            ],
        ),
    ]
