# Generated by Django 3.0.4 on 2020-04-20 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ciudad', '0001_initial'),
        ('Empresa', '0002_auto_20200419_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ciudad.Ciudad'),
        ),
    ]
