# Generated by Django 3.0.4 on 2020-04-20 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Partido', '0001_initial'),
        ('DetallePartido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepartido',
            name='Partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Partido.Partido'),
        ),
    ]
